services:
  - type: web
    name: zangos
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CASHFREE_APP_ID
        sync: false
      - key: CASHFREE_SECRET_KEY
        sync: false
      - key: CASHFREE_ENV
        value: production
